### ISSUE TITLE
Dailymotion

### ISSUE THREAD

**Issue by HellboyPI** [anudeepND/adservers#1]
Hello! Thank you for your effort!
Possible problems:
s2.dmcdn.net, static2.dmcdn.net - blocks thumbnail images of the videos on [dailymotion.com](http://www.dailymotion.com/)
lx1.dyncdn.cc - blocks movie/tv cover images on [1337x.to](http://1337x.to/home/)
vid3.ec.dmcdn.net -  I've found this domain also in your list. Not sure what type of videos it blocks on dailymotion. Ads-videos? Could be a false positive too.

**Comment by HellboyPI** [comment]
player.ooyala.com - The [Ooyala Player](http://www.ooyala.com/resources/video-player). Example, used on accuweather.com to play [videos](https://www.accuweather.com/en/videos/).

**Comment by anudeepND** [comment]
Hi there! Thanks for reporting. I removed 
`player.ooyala.com`
`s1.yimg.com`
`s2.dmcdn.net`
`s.yimg.com`
`static2.dmcdn.net`
`vid3.ec.dmcdn.net`
`api.dailymotion.com`

Now yahoo.com, dailymotion.com and AccuWeather videos works fine.
Update your adlist to apply the changes.

**Comment by anudeepND** [comment]
Images on 1337x.to loads with `lx1.dyncdn.cc`

![screenshot_2017-09-19-16-02-41-224_com android chrome](https://user-images.githubusercontent.com/26179946/30589103-bbec3b12-9d56-11e7-8177-4f7138b833d1.png)

![screenshot_2017-09-19-16-02-51-858_com android chrome](https://user-images.githubusercontent.com/26179946/30589104-bc29ab32-9d56-11e7-9ca7-72c40edd3877.png)

**Comment by HellboyPI** [comment]
api.ipify.org , dl.dropboxusercontent.com , login.live.com , m.hotmail.com , msftncsi.com , pricelist.skype.com , s.gateway.messenger.live.com , ui.skype.com

These domains (so far) are on your adservers list and on your whitelist. Is this intentionally, or? To avoid confusion, it would be good to remove the false positives from the adservers list.

**Comment by anudeepND** [comment]
I removed them, most of the Microsoft related sites were added without checking by [this](https://github.com/anudeepND/adservers/commit/be35995b09ee93851a57bed36d52f435f4ac0cfb#diff-cc22cd07c68c578554231f7e53fe7de8) commit.

**Comment by anudeepND** [comment]
@HellboyPI  Thanks again for finding out these domains!
