### ISSUE TITLE
symcb.com Domains Prevent Symantec Certificate Revocation Checking

### ISSUE THREAD

**Issue by IanOliver** [anudeepND/adservers#2]
Currently symcb.com is included in the wildcard file, but blocking this whole domain and its subdomains prevents HTTPS certificate revocation status checking in Chrome, resulting in HTTPS/certificate errors.

gp.symcb.com and tn.symcb.com are also included in the adservers file. I cannot yet confirm if these are used for certificate purposes or something else, but I managed to fix the issue by removing symcb.com from my wildcards.

Edit: example site to test with https://symantec.com. I am using Chrome 62 on Windows 10.

**Comment by anudeepND** [comment]
@IanOliver Thanks for reporting :) Removed domains related to symcb.com from both the files. Let me know if you face any problems with the list.

**Comment by IanOliver** [comment]
@anudeepND No problem, thanks for the list :)

**Comment by anudeepND** [comment]
If you are blocking millions of domains with pi-hole, (whitelist)[https://github.com/anudeepND/whitelist] file might come in handy...
