### ISSUE TITLE
false positives

### ISSUE THREAD

**Issue by notracking** [anudeepND/adservers#3]
Hi there,

I've been looking into adding your list to my auto updated dnsmasq filter, though I found quite a lot of possible false calls.

You might want to consider removing the following items:

vmall.com
taobao.com
toplinkxchange.com
shellcat.ru
sigidwiki.com
jappy.tv
kingsoft.com
skyrock.mobi
skyrock.net
pwnews.net
rusnext.ru
nianticlabs.com
nikopik.com
nordpresse.be
nrj.fr
minimilitiahackcheats.com
magicbricks.com
launchforth.io
ksosoft.com
hideipaddr.com
fairtop.in
fedsig.com
fireeye.com
dailymaza.co
delcomeyersdale.com
columbiarecords.com
birddl.com
azadmob.in

**Comment by anudeepND** [comment]
@notracking Thanks for reporting!
